MISC: Do some basic input validation for the rsyslog_helper script
There will be more robust input validation in the web UI, as I know how to
format Javascript regexes better than Bash ones. But the script will check 
that the parameter passed is in the required format (IP_ADDRESS:PORT), 
else it will abort.

diff --git a/Installer/nova_rsyslog_helper b/Installer/nova_rsyslog_helper
--- a/Installer/nova_rsyslog_helper
+++ b/Installer/nova_rsyslog_helper
@@ -2,11 +2,23 @@
 
 TARGET=$1
 FILE=/etc/rsyslog.d/40-nova.conf
+NOT_IP=^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\:[0-9]{1,5}$
 
 if [[ -z $TARGET ]]
 then
 {
   echo 'Usage: nova_rsyslog_helper TARGET_IP:TARGET_PORT'
+  exit 1
+}
+fi
+if [[ $TARGET =~ $NOT_IP ]]
+then
+{
+  echo "Matched" >/dev/null
+}
+else
+{
+  echo "Invalid IP, aborting..."
   exit 1
 }
 fi
